In [1]:
from basic_fcn import *
from ModelHandler import *
config = load_config('./config.yaml')
config['batch_size']=1
config['model_name']='both_flip'
model = FCN(n_class = 10)
handler = ModelHandler(model, config)



In [21]:
import torch
#calculate, mean,std for input3 channels
all_mean = []
all_std = []
with torch.no_grad():  # we don't need to calculate the gradient in the validation/testing
    for iter, (input, label) in enumerate(handler.test_loader):
        # both inputs and labels have to reside in the same device as the model's
        channel1_mean = torch.mean(input[:,0,:,:]).item()
        channel2_mean = torch.mean(input[:,1,:,:]).item()
        channel3_mean = torch.mean(input[:,2,:,:]).item()
        
        channel1_std = torch.std(input[:,0,:,:]).item()
        channel2_std = torch.std(input[:,1,:,:]).item()
        channel3_std = torch.std(input[:,2,:,:]).item()
        
        all_mean.append([channel1_mean, channel2_mean,channel3_mean])
        all_std.append([channel1_std, channel2_std,channel3_std])
        
        

In [23]:
np.mean(np.array(all_std), axis = 0)

array([1.10600361, 1.13916147, 1.15539613])

In [24]:
np.mean(np.array(all_mean), axis = 0)

array([-0.24527167, -0.11345779,  0.05439441])

In [19]:
channel1_mean = torch.mean(input[:,0,:,:]).item()


array([-1.5870366, -1.6041614, -1.6212862, ..., -1.7582842, -1.7411594,
       -1.7240347], dtype=float32)

In [20]:
channel1_mean

-0.18895071744918823

In [15]:
all_std.item

[[tensor(1.2927), tensor(1.3052), tensor(1.2551)],
 [tensor(1.4248), tensor(1.4593), tensor(1.5244)],
 [tensor(1.0885), tensor(1.0651), tensor(1.1047)],
 [tensor(0.9926), tensor(1.1047), tensor(1.1881)],
 [tensor(1.0674), tensor(1.0934), tensor(1.0331)],
 [tensor(1.0348), tensor(0.9804), tensor(0.9462)],
 [tensor(1.2500), tensor(1.2782), tensor(1.3407)],
 [tensor(1.1161), tensor(1.1289), tensor(1.1661)],
 [tensor(1.2163), tensor(1.2392), tensor(1.1403)],
 [tensor(0.9111), tensor(0.8909), tensor(0.9163)],
 [tensor(1.2050), tensor(1.2723), tensor(1.3086)],
 [tensor(1.2625), tensor(1.2967), tensor(1.2731)],
 [tensor(1.2805), tensor(1.2899), tensor(1.2410)],
 [tensor(1.2332), tensor(1.1862), tensor(1.1333)],
 [tensor(1.2853), tensor(1.2874), tensor(1.3464)],
 [tensor(1.0874), tensor(1.0815), tensor(1.0991)],
 [tensor(0.9459), tensor(0.9944), tensor(1.0061)],
 [tensor(1.3302), tensor(1.4071), tensor(1.4157)],
 [tensor(1.2772), tensor(1.3088), tensor(1.3487)],
 [tensor(1.2288), tensor(1.3270

In [12]:
channel2_mean

tensor(0.4725)

In [13]:
channel3_mean

tensor(0.6077)